### ISSUE TITLE
store labels and layers in prefix directories

### ISSUE THREAD

**Issue by matko** [terminusdb/terminus-store#12]
file systems have a limited amount of entries that can exist in a directory, either as a hard limit or as a point where file operations become too expensive.

Right now, when using the directory store backend, layers and labels are all written to the same subdirectory, without any sublevels. We should introduce subdirectories to limit the amount of files per directory.

**Comment by rrooij** [comment]
Prefix dirs are now implemented. We'll see how it performs!
