### ISSUE TITLE
Are subject_id and object_node_id in layer identical?

### ISSUE THREAD

**Issue by spl** [terminusdb/terminus-store#26]
Consider the code referenced below. Should they be consolidated?

https://github.com/terminusdb/terminus-store/blob/b80ddce65323a0a3423df5744f8f41ab87fcbd65/src/layer/base.rs#L145-L147

https://github.com/terminusdb/terminus-store/blob/b80ddce65323a0a3423df5744f8f41ab87fcbd65/src/layer/base.rs#L153-L155

https://github.com/terminusdb/terminus-store/blob/b80ddce65323a0a3423df5744f8f41ab87fcbd65/src/layer/child.rs#L240-L255

https://github.com/terminusdb/terminus-store/blob/b80ddce65323a0a3423df5744f8f41ab87fcbd65/src/layer/child.rs#L274-L289

**Comment by matko** [comment]
They are the same, and the only reason we got it in 2 versions is that I wanted to hide this detail in the API, so that a library user doesn't know they are the same. This would allow us to later on change things around so that they are in fact not the same. So far this hasn't happened though.
